/* Calendar dates use the device's local timezone; UTC arithmetic avoids DST drift. */
const RACE_KEY='athleticRacePrepV1';
function raceDayKey(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
function raceDayNumber(key){if(!/^\d{4}-\d{2}-\d{2}$/.test(key||''))return NaN;const [y,m,d]=key.split('-').map(Number);const n=Date.UTC(y,m-1,d);return new Date(n).toISOString().slice(0,10)===key?n/86400000:NaN;}
function raceShift(key,days){return new Date((raceDayNumber(key)+days)*86400000).toISOString().slice(0,10);}
function raceLabel(key){return new Date(key+'T12:00:00').toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'});}
function racePhase(days){return days<0?'finished':days===0?'race':days<=3?'fuel':days<=7?'taper':'build';}
let raceState;try{raceState=JSON.parse(localStorage.getItem(RACE_KEY)||'null');}catch{}
if(!raceState||typeof raceState!=='object')raceState={};
raceState.date=raceState.date||'';raceState.checks=raceState.checks||{};raceState.readiness=raceState.readiness||{};
function saveRaceState(next){try{localStorage.setItem(RACE_KEY,JSON.stringify(next));raceState=next;return true;}catch{showToast('Unable to save Race Prep. Keep this page open and try again.');return false;}}
const raceTab=document.createElement('div');raceTab.className='tab';raceTab.dataset.tab='race';raceTab.textContent='Race';document.querySelector('[data-tab=train]').after(raceTab);
const racePanel=document.createElement('div');racePanel.className='panel';racePanel.id='panel-race';document.querySelector('main').append(racePanel);
const RACE_RUNS=[[-18,3,4,'Easy run'],[-16,5,5,'Easy run'],[-14,6.5,7,'Long easy run'],[-12,3,4,'Easy run'],[-10,4,5,'Easy run'],[-8,7.5,8,'Last long easy run'],[-5,2,3,'Short easy run'],[-3,2,3,'Short easy run']];
function raceSchedule(){return raceState.date?RACE_RUNS.map(([offset,min,max,title])=>({date:raceShift(raceState.date,offset),min,max,title})):[];}
function raceMilesOn(day){return log.reduce((sum,e)=>{
 if(e.type!=='run'||raceDayKey(new Date(e.date))!==day)return sum;
 let miles=0;
 if(e.outdoor){if(e.outdoor.kind==='run')miles=Number(e.outdoor.distanceMiles)||0;}
 else if(e.runMetrics)miles=Number(e.runMetrics.easyMiles)||0;
 else {const value=e.runData?.easy||e.runData?.run||'';const match=/^\s*(\d+(?:\.\d+)?)\s*mi\b/.exec(value);if(match)miles=Number(match[1]);}
 return sum+(Number.isFinite(miles)&&miles>0?miles:0);
 },0);}
function raceCheck(id,text,auto=false){const key=`${raceState.date}:${id}`;return `<label class="race-check ${auto||raceState.checks[key]?'is-done':''}"><input type="checkbox" data-race-check="${escapeText(key)}" ${auto||raceState.checks[key]?'checked':''} ${auto?'disabled':''}><span>${escapeText(text)}${auto?'<small>Matched from Run / Progress</small>':''}</span></label>`;}
function raceRunCard(run,today){const miles=raceMilesOn(run.date),auto=miles+0.001>=run.min,sore=raceState.readiness[run.date]?.legs==='Sore',range=run.min===run.max?run.min:`${run.min}–${run.max}`;return `<div class="race-run ${sore?'race-reassess':''}"><small>${raceLabel(run.date)}${run.date===today?' · Today':''}</small>${raceCheck('run:'+run.date,`${run.title} · ${range} mi`,auto)}${sore?'<p class="race-warning">Sore legs — reassess this run before starting. The plan has not changed.</p>':''}<p>${miles>0?`${miles.toFixed(2)} mi logged · `:''}Conversational effort. Planned run/walk is welcome: 9 min run / 1 min walk.</p><button type="button" class="race-link" data-race-run="${run.date}">Log run</button></div>`;}
function raceTrend(today=raceDayKey()){
 const points=Object.entries(raceState.readiness).filter(([day,r])=>day<=today&&Number(r.weight)>0).sort(([a],[b])=>a.localeCompare(b));
 const average=(start,end)=>{const values=points.filter(([d])=>d>=start&&d<=end).map(([,r])=>Number(r.weight));return {n:values.length,value:values.length?values.reduce((a,b)=>a+b,0)/values.length:null};};
 const recent=average(raceShift(today,-6),today),previous=average(raceShift(today,-13),raceShift(today,-7));
 return {...recent,change:recent.value!==null&&previous.value!==null?recent.value-previous.value:null,points:points.filter(([d])=>d>=raceShift(today,-13))};
}
function raceTrendHTML(today){const trend=raceTrend(today);let graphic='';if(trend.points.length>1){const values=trend.points.map(([,r])=>Number(r.weight)),lo=Math.min(...values)-1,hi=Math.max(...values)+1;const points=trend.points.map(([d,r])=>`${10+(raceDayNumber(d)-raceDayNumber(raceShift(today,-13)))/13*280},${65-(Number(r.weight)-lo)/(hi-lo)*50}`).join(' ');graphic=`<svg viewBox="0 0 300 80" role="img" aria-label="Morning weight observations over the last 14 days"><polyline points="${points}" fill="none" stroke="currentColor" stroke-width="3"/></svg>`;}return `<div class="race-trend"><small>7-DAY MORNING WEIGHT AVERAGE</small><strong>${trend.value===null?'—':trend.value.toFixed(1)+' lb'}</strong><p>${trend.n?`${trend.n} of 7 mornings recorded`:'Add a morning weight to start your trend.'}${trend.change!==null?` · ${trend.change>=0?'+':''}${trend.change.toFixed(1)} lb vs prior 7 days`:''}</p>${graphic}<p>Watch the rolling trend, not daily changes. No target to force nine pounds off before race day.</p></div>`;}
function renderRace(){
 const today=raceDayKey(),days=raceDayNumber(raceState.date)-raceDayNumber(today),phase=racePhase(days),hasDate=Number.isFinite(days),runs=raceSchedule(),ready=raceState.readiness[today]||{};
 racePanel.innerHTML=`<section class="race-hero"><small>10-MILE RACE PREP</small><h2>${hasDate?(days>0?`${days}<span> days to go</span>`:days===0?'Race day':'Race complete'):'Your next starting line'}</h2><p>${hasDate?raceLabel(raceState.date)+' · '+(days<0?'Your checklist is saved. Set your next date when ready.':'Easy effort. Consistent fuel. Arrive ready.'):'Set the exact race date to build your countdown.'}</p><label>Race date<input type="date" id="raceDate" value="${escapeText(raceState.date)}"></label><button type="button" id="raceSetDate">${hasDate?'Update date':'Set race date'}</button></section>
 ${hasDate&&days>=0?`<section class="race-section"><h3>Today <small>${raceLabel(today)}</small></h3>${days<=7?'<p class="race-badge">Hybrid · Reduced Leg Volume</p><p class="backup-note">Keep strength comfortable: fewer lower-body sets, no grinding reps. Keep the final few days easy.</p>':''}${days<=3?'<p class="race-badge">Race fueling · maintenance, not a deficit</p>':''}${runs.filter(r=>r.date===today).map(r=>raceRunCard(r,today)).join('')||`<p class="backup-note">${days===0?'Your race-morning checklist is below.':days<=2?'Easy walking or rest today.':'No prescribed run today. Recovery, easy walking or comfortable Hybrid strength.'}</p>`}
 ${raceCheck(today+':nutrition',days<=3?'Eat around maintenance; stop actively pursuing a calorie deficit.':'Nutrition target: roughly 2,200–2,400 calories; fuel more if needed for the run and recovery.')}
 ${raceCheck(today+':protein','Aim for 160–190 g protein across the day.')}
 ${raceCheck(today+':carbs',days<=3?'Increase familiar carbohydrate-rich foods; keep foods familiar.':'Keep carbs, especially before and after runs. Fast food: lean protein + useful carbs.')}
 ${raceCheck(today+':hydration','Maintain normal hydration; avoid deliberately overhydrating.')}
 ${days<=3?raceCheck(today+':easy','Keep activity easy and avoid unfamiliar foods.'):''}
 <div class="race-actions"><button type="button" data-race-tab="train">Hybrid plan</button><button type="button" data-race-tab="free">Log other workout</button><button type="button" data-race-tab="log">Progress</button></div></section>`:''}
 <section class="race-section"><h3>Daily readiness</h3><p class="backup-note">${raceLabel(today)} · Optional check-in</p><div class="race-readiness"><label>Morning weight · lb<input id="raceWeight" type="number" min="50" max="700" step="0.1" value="${escapeText(ready.weight||'')}" placeholder="Morning, before food"></label><label>Sleep · hours<input id="raceSleep" type="number" min="0" max="24" step="0.5" value="${escapeText(ready.sleep??'')}"></label><label>Legs<select id="raceLegs"><option value="">Choose</option>${['Fresh','Normal','Heavy','Sore'].map(x=>`<option ${ready.legs===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Notes<textarea id="raceNotes" maxlength="1000" rows="2">${escapeText(ready.notes||'')}</textarea></label></div><button type="button" id="raceSaveReady">Save check-in</button>${raceTrendHTML(today)}</section>
 ${hasDate?`<section class="race-section"><h3>This Week</h3><p class="backup-note">Upcoming runs, next seven days. Reassess pain or poor recovery; missed runs are not squeezed in.</p>${runs.filter(r=>r.date>today&&r.date<=raceShift(today,6)).map(r=>raceRunCard(r,today)).join('')||'<p>No scheduled runs in this window.</p>'}${runs.some(r=>r.date>raceShift(today,6)&&r.date<raceShift(raceState.date,-7))?`<details><summary>Next week / build-up</summary>${runs.filter(r=>r.date>raceShift(today,6)&&r.date<raceShift(raceState.date,-7)).map(r=>raceRunCard(r,today)).join('')}</details>`:''}<details><summary>Full schedule & earlier runs</summary>${runs.map(r=>raceRunCard(r,today)).join('')}</details></section>
 <details class="race-section" ${days>=0&&days<=7?'open':''}><summary>Race Week</summary><p class="race-badge">${raceLabel(raceShift(raceState.date,-7))} onward · Reduced Leg Volume</p>${runs.filter(r=>r.date>=raceShift(raceState.date,-7)).map(r=>raceRunCard(r,today)).join('')}<p class="backup-note">Then easy walking/rest before race day. In the final 72 hours, Today automatically switches to maintenance eating, familiar carbs and normal hydration.</p></details>
 <details class="race-section" ${days===0?'open':''}><summary>Race Day</summary><p class="backup-note">${raceLabel(raceState.date)} · Morning checklist</p>${[
 ['breakfast','Eat approximately 60–100 g carbohydrate 2–3 hours before the start.'],['drink','Drink normally; avoid deliberately overhydrating.'],['fuel','Bring the fuel you practiced with.'],['hourly','Plan approximately 30–60 g carbohydrate per hour during the race.'],['start','Start conservatively.'],['walk','Use planned walk breaks before you are exhausted.']].map(([id,label])=>raceCheck('morning:'+id,label)).join('')}</details>`:''}`;
 document.getElementById('raceSetDate').onclick=()=>{const date=document.getElementById('raceDate').value;if(!Number.isFinite(raceDayNumber(date))){showToast('Choose a valid race date.');return;}if(date!==raceState.date&&raceState.date&&!confirm('Use this race date? Checklists are kept separately for each race date; readiness history stays.'))return;if(saveRaceState({...raceState,date})){renderRace();updateRaceIntegration();}};
 document.getElementById('raceSaveReady').onclick=()=>{const weight=document.getElementById('raceWeight').value,sleep=document.getElementById('raceSleep').value,legs=document.getElementById('raceLegs').value,notes=document.getElementById('raceNotes').value.trim();if((weight&&(!Number.isFinite(Number(weight))||Number(weight)<50||Number(weight)>700))||(sleep&&(!Number.isFinite(Number(sleep))||Number(sleep)<0||Number(sleep)>24))){showToast('Check weight (50–700 lb) and sleep (0–24 hours).');return;}if(saveRaceState({...raceState,readiness:{...raceState.readiness,[today]:{weight,sleep,legs,notes}}})){renderRace();updateRaceIntegration();showToast('Readiness saved ✓');}};
}
function updateRaceIntegration(){
 const days=raceDayNumber(raceState.date)-raceDayNumber(raceDayKey());
 document.querySelectorAll('.race-hybrid-note').forEach(el=>el.remove());
 if(days>=0&&days<=7){document.querySelectorAll('[id^="panel-hybrid-"] .workout-header').forEach(header=>{const note=document.createElement('p');note.className='race-hybrid-note race-badge';note.textContent='Race Week · Reduced Leg Volume';header.after(note);});}
 const status=document.getElementById('raceProgress');if(status)status.innerHTML=`<h3>Race Prep · readiness</h3>${raceTrendHTML(raceDayKey())}<button type="button" class="backup-button" onclick="document.querySelector('[data-tab=race]').click()">Open Race Prep</button><details><summary>Recent check-ins</summary>${Object.entries(raceState.readiness).sort(([a],[b])=>b.localeCompare(a)).slice(0,14).map(([day,r])=>`<p>${raceLabel(day)} · ${escapeText(r.weight||'—')} lb · ${escapeText(r.sleep??'—')} h sleep · ${escapeText(r.legs||'—')}${r.notes?'<br>'+escapeText(r.notes):''}</p>`).join('')||'<p>No check-ins yet.</p>'}</details>`;
}
document.addEventListener('DOMContentLoaded',()=>{
 const progress=document.createElement('section');progress.id='raceProgress';progress.className='race-section';document.getElementById('panel-log').append(progress);
 // Keep six usable bottom tabs; Challenge stays accessible from Intervals.
 document.querySelector('[data-tab=gtg]').hidden=true;
 const challenge=document.createElement('button');challenge.className='backup-button';challenge.textContent='Open push-up challenge';challenge.onclick=()=>document.querySelector('[data-tab=gtg]').click();document.getElementById('panel-emom').append(challenge);
 racePanel.addEventListener('change',e=>{const key=e.target.dataset.raceCheck;if(key){if(saveRaceState({...raceState,checks:{...raceState.checks,[key]:e.target.checked}}))renderRace();else e.target.checked=!e.target.checked;}});
 racePanel.addEventListener('click',e=>{const tab=e.target.closest('[data-race-tab]');if(tab)document.querySelector(`[data-tab=${tab.dataset.raceTab}]`).click();const run=e.target.closest('[data-race-run]');if(run){document.querySelector('[data-tab=run]').click();document.getElementById('manual-run-date').value=run.dataset.raceRun;persistDraft();document.getElementById('easy-dist').focus();}});
 queueMicrotask(()=>{for(const name of ['saveRun','saveOutdoor','saveWorkout','saveFreeWorkout','deleteEntry']){const original=window[name];window[name]=function(...args){const before=log.length;const result=original(...args);if(name==='saveRun'&&log.length>before){document.getElementById('manual-run-date').value='';persistDraft();}renderRace();updateRaceIntegration();return result;};}renderRace();updateRaceIntegration();});
 document.addEventListener('click',e=>{if(e.target.closest('.tab')){renderRace();updateRaceIntegration();}});
 document.addEventListener('visibilitychange',()=>{if(!document.hidden){renderRace();updateRaceIntegration();}});
 let day=raceDayKey();setInterval(()=>{const now=raceDayKey();if(now!==day){day=now;renderRace();updateRaceIntegration();}},60000);
});
