// NODE_PATH=/path/to/playwright/node_modules node tests/outdoor.cjs
const {chromium}=require('playwright');const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..');
const server=http.createServer((req,res)=>{const f=path.join(root,req.url==='/'?'index.html':req.url);res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.svg')?'image/svg+xml':f.endsWith('.png')?'image/png':'text/html');try{res.end(fs.readFileSync(f));}catch{res.statusCode=404;res.end();}}).listen(8766);
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{}),args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
await page.goto('http://localhost:8766');
assert.equal(await page.locator('.panel.active').getAttribute('id'),'panel-hybrid-a');
assert.equal(await page.locator('#hybrid-a-exercises .exercise-card').count(),6);
assert.ok(!/carry/i.test(await page.locator('#hybrid-a-exercises').textContent()));
await page.locator('#equip-hybrid-a').selectOption('Commercial Gym');
assert.equal(await page.locator('#exname-hybrid-a-Strength-0').textContent(),'Hack Squat Machine');
assert.equal(await page.locator('#logger-hybrid-a-Strength-0 .complete-btn').count(),3);
await page.locator('#card-hybrid-a-Strength-0 .exercise-header-left').click();
await page.locator('#hybrid-a-Strength-0-s1-reps').fill('8');
await page.locator('#hybrid-a-Strength-0-s1-wt').fill('70');
await page.locator('#hybrid-a-Strength-0-s1-done').click();
await page.reload();
assert.equal(await page.locator('#equip-hybrid-a').inputValue(),'Commercial Gym');
assert.equal(await page.locator('#hybrid-a-Strength-0-s1-reps').inputValue(),'8');
await page.evaluate(()=>saveWorkout('hybrid-a'));
assert.equal(await page.evaluate(()=>log.length),1);
assert.equal(await page.evaluate(()=>log[0].type),'hybrid-a');
assert.ok((await page.locator('#hybridNext button').textContent()).includes('Strength & Control'));
await page.evaluate(()=>saveWorkout('hybrid-a'));assert.equal(await page.evaluate(()=>log.length),1);
await page.locator('#hybridNext button').click();
assert.equal(await page.locator('.panel.active').getAttribute('id'),'panel-hybrid-b');
await page.locator('[data-day=hybrid-d]').click();
await page.evaluate(()=>{document.getElementById('hybrid-d-Strength-0-s1-reps').value='10';saveWorkout('hybrid-d');});
assert.ok((await page.locator('#hybridNext button').textContent()).includes('Strength & Control'));
await page.reload();assert.equal(await page.locator('.panel.active').getAttribute('id'),'panel-hybrid-d');
await page.locator('[data-day=hybrid-a]').click();
for(const width of [320,390,430]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow '+width);}
await page.locator('[data-tab=run]').click();
assert.equal(await page.locator('#gpsDetails').getAttribute('open'),null);
await page.locator('#ruck-time').fill('1:15:00');
await page.locator('#ruck-weight').fill('30');
await page.reload();await page.locator('[data-tab=run]').click();
assert.equal(await page.locator('#ruck-time').inputValue(),'1:15:00');
const before=await page.evaluate(()=>log.length);
await page.evaluate(()=>saveRun());
assert.equal(await page.evaluate(()=>log.length),before+1);
assert.equal(await page.evaluate(()=>log[0].label),'Ruck');
assert.equal(await page.evaluate(()=>log[0].durationMin),75);
assert.ok(await page.evaluate(()=>log[0].calories>0));
assert.equal(await page.locator('#gpsPack').inputValue(),'25','Manual save preserves GPS settings');
await page.evaluate(()=>saveRun());assert.equal(await page.evaluate(()=>log.length),before+1);
await page.locator('#easy-time').fill('12:99');await page.evaluate(()=>saveRun());
assert.equal(await page.evaluate(()=>log.length),before+1,'Reject malformed time');
await page.locator('#easy-time').fill('30');await page.evaluate(()=>saveRun());
assert.equal(await page.evaluate(()=>log[0].durationMin),30);
for(const key of ['a','b','c','d'])assert.equal(await page.locator('#exname-hybrid-'+key+'-Strength-4').textContent(),'Frog Crunches');
for(const [key,name] of [['a','DB Lateral Raise'],['b','DB Standing Calf Raise'],['c','DB Hammer Curl'],['d','Glute Bridge']]) {
  assert.equal(await page.locator('#hybrid-'+key+'-exercises .exercise-card').count(),6);
  await page.evaluate(key=>{const select=document.getElementById('equip-hybrid-'+key);select.value='default';applyHybridMode('hybrid-'+key,select);},key);
  assert.equal(await page.locator('#exname-hybrid-'+key+'-Strength-5').textContent(),name);
}
await page.evaluate(()=>{const select=document.getElementById('equip-hybrid-a');select.value='Commercial Gym';applyHybridMode('hybrid-a',select);});
assert.equal(await page.locator('#exname-hybrid-a-Strength-5').textContent(),'Cable Lateral Raise');
assert.equal(await page.locator('#logger-hybrid-a-Strength-5 .complete-btn').count(),3);
await page.screenshot({path:'/tmp/hybrid-preview.png',fullPage:true});
assert.deepEqual(errors,[]);await browser.close();server.close();console.log('PASS: Hybrid plan, gym set counts, draft recovery, save/deduplication, next-session rotation, optional session, mobile widths.');
})().catch(e=>{console.error(e);process.exit(1);});
