// NODE_PATH=/path/to/playwright/node_modules node tests/outdoor.cjs
const {chromium}=require('playwright');const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..');
const server=http.createServer((req,res)=>{const f=path.join(root,req.url==='/'?'index.html':req.url);res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.svg')?'image/svg+xml':f.endsWith('.png')?'image/png':'text/html');try{res.end(fs.readFileSync(f));}catch{res.statusCode=404;res.end();}}).listen(8766);
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{}),args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
await page.goto('http://localhost:8766');
await page.locator('[data-tab=free]').click();
await page.locator('#freeTitle').fill('Travel workout <test>');
await page.locator('#freeName').fill('Bench Press');await page.locator('#freeAdd').click();
await page.locator('[data-ex="0"][data-set="0"][data-field=reps]').fill('10');
await page.locator('[data-ex="0"][data-set="0"][data-field=wt]').fill('40');
await page.locator('#freeEquipment').selectOption('Bodyweight');
await page.locator('#freeName').fill('<img src=x onerror="window.injected=true">');await page.locator('#freeAdd').click();
await page.locator('[data-unit="1"]').selectOption('seconds');
await page.locator('[data-ex="1"][data-set="0"][data-field=reps]').fill('30');
await page.locator('#freeNotes').fill('Custom notes <b>plain text</b>');
await page.reload();
assert.equal(await page.locator('.panel.active').getAttribute('id'),'panel-free');
assert.equal(await page.locator('#freeTitle').inputValue(),'Travel workout <test>');
assert.equal(await page.locator('[data-ex="0"][data-set="0"][data-field=wt]').inputValue(),'40');
const next=await page.locator('#hybridNext').textContent();
await page.locator('#freeSave').click();
assert.equal(await page.evaluate(()=>log.length),1);
assert.equal(await page.evaluate(()=>log[0].sets[0].equipment),'Dumbbell');
assert.equal(await page.evaluate(()=>log[0].sets[0].totalVol),400);
assert.equal(await page.evaluate(()=>log[0].sets[1].unit),'seconds');
assert.equal(await page.locator('#hybridNext').textContent(),next);
await page.locator('#freeSave').click();assert.equal(await page.evaluate(()=>log.length),1);
await page.locator('[data-tab=log]').click();
assert.ok((await page.locator('.log-sets').textContent()).includes('30 sec'));
assert.equal(await page.evaluate(()=>window.injected),undefined);
assert.equal(await page.locator('.log-sets img').count(),0);
await page.locator('[data-tab=free]').click();
await page.locator('#freeName').fill('Row');await page.locator('#freeAdd').click();
await page.locator('[data-ex="0"][data-set="0"][data-field=wt]').fill('20');
await page.locator('#freeSave').click();assert.equal(await page.evaluate(()=>log.length),1,'Weight alone rejected');
await page.locator('[data-ex="0"][data-set="0"][data-field=reps]').fill('8');
await page.evaluate(()=>{window.originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='trainingLog')throw Error('quota');return originalSetItem.call(this,k,v);};});
await page.locator('#freeSave').click();assert.equal(await page.evaluate(()=>log.length),1,'Failed save preserves history');
assert.equal(await page.locator('[data-ex="0"][data-set="0"][data-field=reps]').inputValue(),'8');
await page.evaluate(()=>Storage.prototype.setItem=originalSetItem);
for(const width of [320,390,430]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow '+width);}
await page.screenshot({path:'/tmp/free-preview.png',fullPage:true});assert.deepEqual(errors,[]);await browser.close();server.close();console.log('PASS: mixed equipment, custom names, timed sets, draft reload, history, plan isolation, validation, save failure, mobile widths.');
})().catch(e=>{console.error(e);process.exit(1);});
